### ISSUE TITLE
There is no Podfile

### ISSUE THREAD

**Issue by hasancc** [ekinakyurek/KuGpa#1]
The podfile for dependencies is probably ignored in your .gitignore file.

You need to add Podfile to git so cocoapods works as intended. You also need to ignore Podfile.lock instead of Podfile in .gitignore

**Comment by ekinakyurek** [comment]
I added podfile and .gitignore to the master branch. However after updating Xcode to 7.1 pods caused the issue https://github.com/CocoaPods/CocoaPods/issues/4420 in the link. Therefore, I will change our html parsing library Kanna to NDHpple and I'll manually add the library without using cocoapods.

**Comment by hasancc** [comment]
I see, then I'm closing this one.

On a side note, I think you SHOULD use CocoaPods for dependency management as much as possible to keep your sanity. As far as I can tell, there are some workarounds for the issue you mentioned. 

If you absolutely can't use cocoapods, you can document the dependencies (i.e in README.md) and ignore them from git.
